/*
** File: C:\Documents and Settings\emeliehe\My Documents\skola\EmbeddedII\lab7vh\r_ex_c.c
** Generated by XMLLauncher v3.9.1.77 x86 2011a
**
** Copyright 1995-2011 Arcticus Systems AB, All rights reserved.
** The format and content in the File is protected by copyright.
** The File is furnished under a licence and may only be used in
** accordance with the terms of this licence.
** Rubus® is a registered trademark to which Arcticus has all exclusive rights.
*/

/*==========================================================
** Include files
==========================================================*/
#include <basic/bs_basic.h>
#include <basic/bs_log.h>
#include <hal/hal_cfg.h>
#include <rubusOS_cfg.h>
#include "r_ex_bs.h"
#include "r_ex_r.h"
#include "r_ex_g.h"
#include "r_ex_b.h"

/*==========================================================
** blinky0Internal()
==========================================================*/
extern redThreadCB_t blinky0CB;
void blinky0Internal(int_t deadline)

{ R_TYPE_TIME_EXEC execTime;

  bsLogPut(7,R_LOG_EVENT_1);
  R_RED_SET_DEADLINE(&blinky0,deadline)
  R_EXEC_TIME_START(execTime)
  R_RED_KERNEL_EXIT;
  blinky0Main();
  R_RED_KERNEL_ENTER;
  R_EXEC_TIME_STOP(execTime,execTime,0u)
  bsLogPut(7,R_LOG_EVENT_2);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 0
==========================================================*/
extern void redScheduleStart_5(void);
void redScheduleStart_0(void)

{
  bsLogPut(8,R_LOG_EVENT_1);
  R_RED_NEXT(&redScheduleStart_5,5)
  blueActivate(&blueKernel);
  blinky0Internal(10);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 5
==========================================================*/
extern void redScheduleStart_10(void);
void redScheduleStart_5(void)

{
  R_RED_NEXT(&redScheduleStart_10,10)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 10
==========================================================*/
extern void redScheduleStart_15(void);
void redScheduleStart_10(void)

{
  R_RED_NEXT(&redScheduleStart_15,15)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 15
==========================================================*/
extern void redScheduleStart_20(void);
void redScheduleStart_15(void)

{
  R_RED_NEXT(&redScheduleStart_20,20)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 20
==========================================================*/
extern void redScheduleStart_25(void);
void redScheduleStart_20(void)

{
  R_RED_NEXT(&redScheduleStart_25,25)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 25
==========================================================*/
extern void redScheduleStart_30(void);
void redScheduleStart_25(void)

{
  R_RED_NEXT(&redScheduleStart_30,30)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 30
==========================================================*/
extern void redScheduleStart_35(void);
void redScheduleStart_30(void)

{
  R_RED_NEXT(&redScheduleStart_35,35)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 35
==========================================================*/
extern void redScheduleStart_40(void);
void redScheduleStart_35(void)

{
  R_RED_NEXT(&redScheduleStart_40,40)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 40
==========================================================*/
extern void redScheduleStart_45(void);
void redScheduleStart_40(void)

{
  R_RED_NEXT(&redScheduleStart_45,45)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 45
==========================================================*/
extern void redScheduleStart_50(void);
void redScheduleStart_45(void)

{
  R_RED_NEXT(&redScheduleStart_50,50)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 50
==========================================================*/
extern void redScheduleStart_55(void);
void redScheduleStart_50(void)

{
  R_RED_NEXT(&redScheduleStart_55,55)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 55
==========================================================*/
extern void redScheduleStart_60(void);
void redScheduleStart_55(void)

{
  R_RED_NEXT(&redScheduleStart_60,60)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 60
==========================================================*/
extern void redScheduleStart_65(void);
void redScheduleStart_60(void)

{
  R_RED_NEXT(&redScheduleStart_65,65)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 65
==========================================================*/
extern void redScheduleStart_70(void);
void redScheduleStart_65(void)

{
  R_RED_NEXT(&redScheduleStart_70,70)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 70
==========================================================*/
extern void redScheduleStart_75(void);
void redScheduleStart_70(void)

{
  R_RED_NEXT(&redScheduleStart_75,75)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 75
==========================================================*/
extern void redScheduleStart_80(void);
void redScheduleStart_75(void)

{
  R_RED_NEXT(&redScheduleStart_80,80)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 80
==========================================================*/
extern void redScheduleStart_85(void);
void redScheduleStart_80(void)

{
  R_RED_NEXT(&redScheduleStart_85,85)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 85
==========================================================*/
extern void redScheduleStart_90(void);
void redScheduleStart_85(void)

{
  R_RED_NEXT(&redScheduleStart_90,90)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 90
==========================================================*/
extern void redScheduleStart_95(void);
void redScheduleStart_90(void)

{
  R_RED_NEXT(&redScheduleStart_95,95)
  blueActivate(&blueKernel);
}

/*==========================================================
** Red Schedule redScheduleStart Releasetime 95
==========================================================*/
extern void redScheduleStart_0(void);
void redScheduleStart_95(void)

{
  blueActivate(&blueKernel);
}

/*==========================================================
** Rubus OS Initialisation
==========================================================*/
int_t bsRubusInit(void)

{ int_t rcode;

  rcode = bsInit();
  if (rcode != R_OK) {
    return(rcode);
  }

  rcode = redInit(&redScheduleStart);
  if (rcode != R_OK) {
    return(rcode);
  }

  rcode = blueInit();
  if (rcode != R_OK) {
    return(rcode);
  }

  rcode = blueThreadInitAll();
  if (rcode != R_OK) {
    return(rcode);
  }

  return(R_OK);
}

